export enum CommonStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
  SUSPENDED = 'SUSPENDED',
}

export enum AdmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ENROLLED = 'ENROLLED',
  CANCELLED = 'CANCELLED',
}

export enum EnrollmentStatus {
  ACTIVE = 'ACTIVE',
  TRANSFERRED = 'TRANSFERRED',
  PROMOTED = 'PROMOTED',
  WITHDRAWN = 'WITHDRAWN',
  SUSPENDED = 'SUSPENDED',
  GRADUATED = 'GRADUATED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  LEAVE = 'LEAVE',
  HOLIDAY = 'HOLIDAY',
}

export enum PaymentMethod {
  CASH = 'CASH',
  UPI = 'UPI',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CARD = 'CARD',
  CHEQUE = 'CHEQUE',
  ONLINE = 'ONLINE',
  OTHER = 'OTHER',
}

export enum PayrollStatus {
  DRAFT = 'DRAFT',
  CALCULATED = 'CALCULATED',
  REVIEW = 'REVIEW',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum StudentStatus {
  REGISTERED = 'REGISTERED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  WITHDRAWN = 'WITHDRAWN',
  TRANSFERRED = 'TRANSFERRED',
  GRADUATED = 'GRADUATED',
  ALUMNI = 'ALUMNI',
}

export enum GuardianRelationshipType {
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  LEGAL_GUARDIAN = 'LEGAL_GUARDIAN',
  GRANDPARENT = 'GRANDPARENT',
  SIBLING = 'SIBLING',
  OTHER = 'OTHER',
}

export enum StudentDocumentType {
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  GOVERNMENT_ID = 'GOVERNMENT_ID',
  TRANSFER_CERTIFICATE = 'TRANSFER_CERTIFICATE',
  PREVIOUS_MARKSHEET = 'PREVIOUS_MARKSHEET',
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  PASSPORT_PHOTO = 'PASSPORT_PHOTO',
  OTHER = 'OTHER',
}

export enum SequenceType {
  STUDENT = 'STUDENT',
  ADMISSION = 'ADMISSION',
  EMPLOYEE = 'EMPLOYEE',
  INVOICE = 'INVOICE',
  RECEIPT = 'RECEIPT',
  EXPENSE = 'EXPENSE',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum LeaveCategory {
  CASUAL = 'CASUAL',
  SICK = 'SICK',
  ANNUAL = 'ANNUAL',
  MATERNITY = 'MATERNITY',
  PATERNITY = 'PATERNITY',
  UNPAID = 'UNPAID',
  OTHER = 'OTHER',
}

export enum HolidayType {
  NATIONAL = 'NATIONAL',
  RELIGIOUS = 'RELIGIOUS',
  SCHOOL_EVENT = 'SCHOOL_EVENT',
  VACATION = 'VACATION',
  OTHER = 'OTHER',
}
